# Generated by Django 4.1.6 on 2023-03-01 16:47

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_banner', models.BooleanField(default=False)),
                ('banner_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
                ('standard', models.BooleanField(default=False)),
                ('icon_url', models.TextField()),
                ('banner_url', models.TextField()),
                ('new', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client3DS',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('consoleid', models.CharField(max_length=12)),
                ('devicetoken', models.CharField(max_length=21)),
                ('is_terminated', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=3)),
                ('uniquekey', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='redeemableCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('used', models.BooleanField(default=False)),
                ('is_money', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='searchCategory',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('platform_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=25)),
                ('desc', models.TextField(default='')),
                ('thumbnail_url', models.TextField()),
                ('icon_url', models.TextField()),
                ('banner_url', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product_code', models.CharField(max_length=30)),
                ('new', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('in_app_purchase', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1024)),
                ('is_not_downloadable', models.BooleanField(default=False)),
                ('ticket_id', models.CharField(max_length=16)),
                ('ticket', models.TextField()),
                ('size', models.IntegerField(default=0)),
                ('ticket_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopdeckdb.category')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.platform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='wishlistedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.client3ds')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.title')),
            ],
        ),
        migrations.CreateModel(
            name='ownedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.client3ds')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.title')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('thumbnail_url', models.TextField()),
                ('banner_url', models.TextField()),
                ('is_3d', models.BooleanField(default=False)),
                ('moflex_url', models.TextField()),
                ('time_in_sec', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('new', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shopdeckdb.category')),
            ],
        ),
        migrations.CreateModel(
            name='customTitleID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=18)),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.client3ds')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('linked_ds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.client3ds')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
