# Generated by Django 4.1.6 on 2023-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdeckdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedtitle',
            name='version',
            field=models.IntegerField(default=1024),
            preserve_default=False,
        ),
    ]
