# Generated by Django 4.1.7 on 2023-03-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopdeckdb', '0007_alter_client3ds_uniquekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcategory',
            name='platform_list',
            field=models.TextField(verbose_name='Platform List (seperate each platform by a comma)'),
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('itemcode', models.CharField(max_length=16)),
                ('price', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.title')),
            ],
        ),
    ]
