# Generated by Django 4.1.7 on 2023-03-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopdeckdb', '0008_alter_searchcategory_platform_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='limit',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ownedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopdeckdb.client3ds')),
            ],
        ),
    ]
